### ISSUE TITLE
 Removing Sign in with LinkedIn and introducing OpenID

### ISSUE THREAD

**Issue by dzab5** [d3xt3r2909/linkedin_login#91] opened 2023-11-14 15:20 UTC
Given as linkedin recently deprecated the apis this package uses (https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin).

Is there any plan to adjust this package to use Open Id connect? (https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2). 

I am asking because the scopes used by this package of r_profile_lite and r_emailaddress are no longer used, which i believe renders this package obsolete at the moment?

**Comment by d3xt3r2909** [comment] 2023-11-14 19:59
Hey, thanks for raising this issue. Tbh I don't have time lately to check the impact on it, but since Microsoft is being Microsoft  the impact is huge. 

Anyhow will do spike these days on workload and give ETA on upgrade..

**Comment by d3xt3r2909** [comment] 2023-11-14 23:24
Ok just a small update, I made POC and seems like its working. There will be some breaking changes of course for this so cannot just simply patch it.. but it should ready in few next days. 

Documentation for migration of this is really really poor. But in theory from now on when we are creating new app inside linkedin console instead of choosing product sign in, we must include OICD 

<img width="777" alt="image" src="https://github.com/d3xt3r2909/linkedin_login/assets/17637299/d1c13980-8522-4ade-8a20-7256da5c87e3">

Also instead of previously called permissions as you said `r_profile_lite` and `r_emailaddress` there are new once: `openid`, `email`, `profile`. 

This means that API that was before used to get user information will be deprecated too (even they didn't wrote this anywhere; but you cannot use it without `r_profile_lite` and `r_emailaddress`) so instead of this profile this library will start using  https://api.linkedin.com/v2/userinfo ([doc](https://api.linkedin.com/v2/userinfo)) which means that instead of previously complex DTO object

```dart
final LinkedInPersonalInfo? firstName;
  final LinkedInPersonalInfo? lastName;
  final LinkedInProfilePicture? profilePicture;
  final String? userId;
  final String? localizedFirstName;
  final String? localizedLastName;
  LinkedInProfileEmail? email;
  late LinkedInTokenObject token;
```

We will have something like 

```dart
  final String? name;
  final String? lastName;
  final String? givenName;
  final bool? isEmailVerified;
  final String? sub;
  final String? email;
  final String? picture;
  final LinkedInPreferredLocal? locale;
```

This is ofc much more readable and easier to access info, but will also mean introducing breaking changes.

**Comment by d3xt3r2909** [comment] 2023-11-15 12:20
Hey, me once again. 

I publish Prerelease [3.0.0-beta.1](https://pub.dev/packages/linkedin_login/versions/3.0.0-beta.1) of this package. 

Would love to hear feedback from you after trying ;]

**Comment by d3xt3r2909** [comment] 2024-01-10 18:54
Hey @dzab5 did you had chance to test it? 

Thanks

**Comment by RAWAN244** [comment] 2024-01-25 10:43
I tried the example, but it is not working this error occurs "The getter 'sub' isn't defined for the class 'LinkedInUserModel'." 
i need a login with LinkedIn for my app 
any ideas on how can i fix it?

**Comment by d3xt3r2909** [comment] 2024-01-25 14:03
Hey @RAWAN244, 

Issue that you are facing is not (at least) shouldn't be connected with this issue and PR. Could you please open new issue with a bit more details (step to reproduce, video maybe, which version of library ur using etc).

Thanks

**Comment by Thelm76** [comment] 2024-03-15 14:59
There are issues with one of the widgets I made a PR her : #94 

I could not test it yet, as there are changes needed in the backend

**Comment by d3xt3r2909** [comment] 2024-03-18 10:52
Hi @Thelm76  I am not sure how your comment and PR are connected with currently opened issue? Marking it as `hide` but if I am wrong please let me know

**Comment by d3xt3r2909** [comment] 2024-03-18 11:04
Announcement: I am publishing version `3.0.0` of this library (not beta anymore) which means that library is converted to OpenID from version >= 3.0.0. 

Thanks for reporting issue and please create new issue/s if something is wrong with this or any other release.

**Closed by d3xt3r2909** 2024-03-18 11:04 UTC
Labels: resolved, feature request, FAQ, !!!IMPORTANT!!!
