### ISSUE TITLE
getting 401 error

### ISSUE THREAD

**Issue by Raviteja11122** [d3xt3r2909/linkedin_login#11] opened 2020-01-06 14:58 UTC
@d3xt3r2909 
Error description: Failed to get user token Error code: 401

**Comment by d3xt3r2909** [comment] 2020-01-06 16:48
What widget are you using? 
Did you try with example in project? 

Please provide me more informations

**Comment by Raviteja11122** [comment] 2020-01-06 17:06
This is my code

Navigator.push(
      context,
      MaterialPageRoute(
        builder: (BuildContext context) =>
            LinkedInUserWidget(
              redirectUrl: redirectUrl,//"http://ec2-52-66-131-212.ap-south-1.compute.amazonaws.com:8080/",
              clientId: clientId,//"81gc9r3a18u01j",
              clientSecret: clientSecret,//"mOZfcUeDKjwZbwW3",
              onGetUserProfile: (LinkedInUserModel linkedInUser) async{
                print(linkedInUser.token.accessToken);
              },
              catchError: (LinkedInErrorObject error) {
                print('Error description: ${error.description} Error code: ${error.statusCode.toString()}');
              },
            ),
        fullscreenDialog: true,
      ),
    )

**Comment by Raviteja11122** [comment] 2020-01-06 17:07
@d3xt3r2909 
This is my code
`Navigator.push(
      context,
      MaterialPageRoute(
        builder: (BuildContext context) =>
            LinkedInUserWidget(
              redirectUrl: redirectUrl,//"http://ec2-52-66-131-212.ap-south-1.compute.amazonaws.com:8080/",
              clientId: clientId,//"81gc9r3a18u01j",
              clientSecret: clientSecret,//"mOZfcUeDKjwZbwW3",
              onGetUserProfile: (LinkedInUserModel linkedInUser) async{
                print(linkedInUser.token.accessToken);
              },
              catchError: (LinkedInErrorObject error) {
                print('Error description: ${error.description} Error code: ${error.statusCode.toString()}');
              },
            ),
        fullscreenDialog: true,
      ),
    )`

**Comment by d3xt3r2909** [comment] 2020-01-09 09:11
@Raviteja11122 Can you please check also is it working with my example? I have now tested it and works completely fine.

**Comment by d3xt3r2909** [comment] 2020-01-13 09:12
@Raviteja11122  Hello again. 

I have try this with my example from project. But was not able to reproduce this. Can you also try to input your code in my example?

**Comment by defint** [comment] 2020-01-14 11:59
@d3xt3r2909 

debug info from this line:
lib/src/linked_in_authorization_webview.dart:124

![Uploading Bitmap.png…]()

**Comment by Raviteja11122** [comment] 2020-01-20 06:16
@d3xt3r2909 

your example app uses the same plugin right ??
so why it's not working for me. I'm using flutter 1.12 stable 

Note: I didn't test your example project because you said it's working fine

**Comment by d3xt3r2909** [comment] 2020-01-20 20:06
@Raviteja11122  Look, I have tried with your client and secret and redirect URL it works. Also, I have added your code for starting my library it works also. Please look at this [image](https://prnt.sc/qqfocf).

I really don't know how to help you anymore. If you have any new/additional information please let me know. Until then I will close this issue because I cannot reproduce this with the information that you provided to me.

**Comment by d3xt3r2909** [comment] 2020-01-20 20:07
@defint please open a new issue with more description when you are getting this?

**Closed by d3xt3r2909** 2020-01-20 20:06 UTC
Labels: question

**Comment by d3xt3r2909** [comment] 2020-01-20 21:47
I will try to fix this issue with @defint explanation. So this can stay closed.
