### ISSUE TITLE
linkedin_login is incompatible with flutter_html latest version

### ISSUE THREAD

**Issue by memishood** [d3xt3r2909/linkedin_login#67] opened 2022-01-03 22:48 UTC
As you can see the title, I get below error when using these libraries
Error:
```
Because linkedin_login >=2.1.0 depends on webview_flutter ^3.0.0 and flutter_html 2.2.1 depends on webview_flutter ^2.0.4, linkedin_login >=2.1.0 is incompatible with flutter_html 2.2.1.
And because no versions of flutter_html match >2.2.1 <3.0.0, linkedin_login >=2.1.0 is incompatible with flutter_html ^2.2.1.
So, because Webrazzi depends on both flutter_html ^2.2.1 and linkedin_login ^2.1.0, version solving failed.
pub get failed (1; So, because Webrazzi depends on both flutter_html ^2.2.1 and linkedin_login ^2.1.0, version solving failed.)
```

**Comment by d3xt3r2909** [comment] 2022-01-03 23:23
Hi and thanks for opening an issue. 

First of all, this is not a bug at all, as you can see the latest version of this package is using the latest version of the `webview_flutter` plugin, so I would advise you to open the same ticket on mentioned packages/plugins as they didn't upgrade version of `webview_flutter`. 

You could also maybe use versions of this library lower than the latest, but be aware of the latest changes that are mentioned inside the changelog file.

For other ways of resolving the same issues please use stack-overflow. 

I'm closing this issue as this shouldn't consider a bug.

**Closed by d3xt3r2909** 2022-01-03 23:23 UTC
Labels: bug, FAQ
