### ISSUE TITLE
Page reload when keyboard opens

### ISSUE THREAD

**Issue by cledesmarand** [d3xt3r2909/linkedin_login#117] opened 2024-05-07 13:58 UTC
Hello, I am having a problem after updating the Flutter version to 3.19.6. It happened to me in linkedin_login version: ^2.2.1 and when updating to version 3.0.2 as well. The problem itself is when it redirects to the page to log in and I touch to enter the email, the keyboard does not open and the page reloads.

To play it, try it on any device running Android 13. Just log in with LinkedIn and try to enter the credentials.

  - Device: Samsung SM-A035M
  - OS: Android 13
  - Plugin Version: 3.0.2

**Log trace**
```
`E/FrameEvents(26872): updateAcquireFence: Did not find frame.
I/flutter (26872): : WebView is loading (progress : 70%) 
W/cr_media(26872): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/flutter (26872): : WebView is loading (progress : 80%) 
I/chromium(26872): [INFO:CONSOLE(1)] "WARNING: Too many active WebGL contexts. Oldest context will be lost.", source: https://static.licdn.com/sc/h/abxtfdoe63m7bntcqj6owpbhb (1)
I/chromium(26872): [INFO:CONSOLE(1)] "WARNING: Too many active WebGL contexts. Oldest context will be lost.", source: https://static.licdn.com/sc/h/abxtfdoe63m7bntcqj6owpbhb (1)
I/chromium(26872): [INFO:CONSOLE(1)] "WARNING: Too many active WebGL contexts. Oldest context will be lost.", source: https://static.licdn.com/sc/h/abxtfdoe63m7bntcqj6owpbhb (1)
W/cr_media(26872): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/chromium(26872): [INFO:CONSOLE(1)] "WARNING: Too many active WebGL contexts. Oldest context will be lost.", source: https://static.licdn.com/sc/h/473v2cdto9klp3y6gfjcs28u2 (1)
I/chromium(26872): [INFO:CONSOLE(1)] "WARNING: Too many active WebGL contexts. Oldest context will be lost.", source: https://static.licdn.com/sc/h/473v2cdto9klp3y6gfjcs28u2 (1)
I/chromium(26872): [INFO:CONSOLE(1)] "WARNING: Too many active WebGL contexts. Oldest context will be lost.", source: https://static.licdn.com/sc/h/473v2cdto9klp3y6gfjcs28u2 (1)
I/flutter (26872): : WebView is loading (progress : 100%) 
I/flutter (26872): : WebView is loading (progress : 100%) 
I/flutter (26872): : Page finished loading:

I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/chromium(26872): [INFO:socket_udp.cc(436)] sendto() has failed twice returning a  transient error net::ERR_ADDRESS_UNREACHABLE. Dropping the packet.
I/ViewRootImpl@4976d95[MainActivity](26872): MSG_WINDOW_FOCUS_CHANGED 0 0`
```

**Comment by cledesmarand** [comment] 2024-05-16 13:48
> Hey thanks for opening will take a look soon

Hello, I hope you have a good day. Any news on the problem?

**Comment by d3xt3r2909** [comment] 2024-05-17 06:43
Hey @cledesmarand , 

I couldn't reproduce this on simulator tested with latest Android SDK + one that you mentioned, no success, good be something with play services related. Anyhow going a bit deeper, I figure out that Android 13 have issue with not opening keyboard if web view is not using surface approach. So I introduce this part in my plugin in version `3.0.5`. 

Could you please use `linkedin_login 3.0.5` and tell me is there any improvement. Many thanks!

**Comment by d3xt3r2909** [comment] 2024-05-17 13:25
Hey, 

interesting. Could you please try with running example project from newest library version (v3.0.5) and see is it working?

**Comment by cledesmarand** [comment] 2024-05-20 12:34
@d3xt3r2909 I tried downloading the example project and it works fine. I'm going to make adjustments to my project. Thanks for the support.

**Comment by d3xt3r2909** [comment] 2024-05-20 12:50
Okey, sorry I couldn't help more. If u can please share what was issue so that I can mark this issue as FAQ. Thanks a lot!

**Comment by cledesmarand** [comment] 2024-05-20 16:58
Well the solution was quite strange, I didn't update anything, I just made these changes to my code:
I only defined the widget as `final`.
```
final page = LinkedInUserWidget(...);

await Navigator.push(
      context,
      MaterialPageRoute(
        fullscreenDialog: true,
        builder: (final BuildContext context) => page,
      ),
    );
```

**Comment by d3xt3r2909** [comment] 2024-05-21 05:34
hmm interesting as this way around context is taken from parent, and not from builder.. anyhow I am glad that we resolved it! I am marking it as close then but feel free to reopen if you have anything related 🙏

**Closed by d3xt3r2909** 2024-05-21 05:34 UTC
Labels: bug
